---

- name: Install EPEL Repo
  yum:
    name:  epel-release
    state: latest

- name: Install Ocserv + deps
  yum:
    name:  '{{ item }}'
    state: present
  with_items:
    - ocserv
    - liboath
    - pam_oath
