---

- name: Create config-per-user path
  file:
    path:  "{{ ocserv_config['config_per_user'] }}"
    group: "{{ ocserv_config['run_as_group'] }}"
    mode:  0750
    state: directory

- name: Add per-user configs
  template:
    src:   config-per.j2
    dest:  "{{ ocserv_config['config_per_user'] }}/{{ item['name'] }}"
    group: "{{ ocserv_config['run_as_group'] }}"
    mode:  0640
  with_items: '{{ ocserv_users }}'
  when:
    - item.options is defined
  notify: reload ocserv
