---

- name: Create config-per-user path
  file:
    path:  '{{ ocserv_config_per_user_path }}'
    group: '{{ ocserv_group }}'
    mode:  0750
    state: directory

- name: Add per-user configs
  template:
    src:   config-per-user.j2
    dest:  '{{ ocserv_config_per_user_path }}/{{ item.name }}'
    group: '{{ ocserv_group }}'
    mode:  0640
  with_items: '{{ ocserv_users }}'
  when:
    - item.config_per_user is defined
  notify: reload ocserv

- name: Add PAM users
  user:
    name:       '{{ item.name }}'
    password:   '{{ item.password | default("") }}'
    shell:      /sbin/nologin
    createhome: no
  with_items:
    - '{{ ocserv_users }}'
  when:
    - ocserv_auth_method | lower == 'pam'
